"""Commercial subscription matrix — mirrors the pricing brief.

Single source for the seed script. Cell values are display strings:
"In" prefix ("✔ Included") renders green, "✖" renders muted.
"""

C = "community"
E = "enterprise"
K = "critical"
S = "sovereign"
YES = "✔ Included"
NO = "✖"

PLANS: list[dict] = [
    {
        "slug": C,
        "name": "Community / Research",
        "price_month_cents": 0,
        "price_display": "€0",
        "per_node": False,
        "target": "Developers, Academia",
        "deployment": "Self-Hosted (Local Only)",
        "node_capacity": "Max 1 Node (Lab: 3 Nodes)",
        "licensing": "FOSS (Apache/MIT)",
        "support": "Community / Discord",
        "cta_label": "Clone on GitHub",
        "cta_href": "https://github.com/kamisaberi/sentinel-stack",
        "sort_order": 0,
    },
    {
        "slug": E,
        "name": "Enterprise IT",
        "price_month_cents": 29900,
        "price_display": "€299",
        "per_node": True,
        "target": "Corporate IT, Cloud, FinTech",
        "deployment": "Cloud Hybrid (SaaS + Edge)",
        "node_capacity": "Unlimited",
        "licensing": "SaaS JWT / Commercial EULA",
        "support": "99.9% Cloud SLA, Standard",
        "cta_label": "Start 14-Day Cloud Trial",
        "cta_href": "https://app.aryorithm.com/portal/register",
        "sort_order": 1,
    },
    {
        "slug": K,
        "name": "Critical Infrastructure (OT)",
        "price_month_cents": 69900,
        "price_display": "€699",
        "per_node": True,
        "target": "Substation, Factory, Hospital",
        "deployment": "Hybrid or 100% Air-Gapped",
        "node_capacity": "Unlimited",
        "licensing": "Commercial Air-Gapped (.lic)",
        "support": "24/7/365 L3, 15-min Critical",
        "cta_label": "Request 14-Day Shadow Pilot",
        "cta_href": "/contact",
        "sort_order": 2,
    },
    {
        "slug": S,
        "name": "Sovereign Defense",
        "price_month_cents": None,
        "price_display": "Custom",
        "per_node": True,
        "target": "Defense, Nuclear, Classified",
        "deployment": "100% Air-Gapped Sovereign",
        "node_capacity": "Unlimited",
        "licensing": "Air-Gapped Hardware Dongle",
        "support": "Dedicated On-Site Team",
        "cta_label": "Request Sovereign Consultation",
        "cta_href": "/contact?tier=defense",
        "sort_order": 3,
    },
]

ITEMS: list[dict] = [
    # ---- 8 software tiers ----
    {"category": "software_tier", "item_key": "t1-xinfer", "item_label": "Tier 1: xinfer-essential (libxinfer.so)",
     "item_sub": "Apache 2.0 (Open Source)", "values": {C: YES, E: YES, K: YES, S: YES}},
    {"category": "software_tier", "item_key": "t2-blackbox", "item_label": "Tier 2: blackbox-essential (libblackbox.so)",
     "item_sub": "Apache 2.0 / GPLv2 (Open Source)", "values": {C: YES, E: YES, K: YES, S: YES}},
    {"category": "software_tier", "item_key": "t3-sentinel", "item_label": "Tier 3: blackbox-sentinel (Appliance Daemon)",
     "item_sub": "C++ LicenseManager Ed25519 Key",
     "values": {C: "Limited (5 Modules)", E: "✔ Included (IT Tier)", K: "✔ Included (Full OT)", S: "✔ Included (Custom Silicon)"}},
    {"category": "software_tier", "item_key": "t4-forge", "item_label": "Tier 4: xinfer-forge (forge-cli)",
     "item_sub": "Automated Safety Gate in forge-cli",
     "values": {C: "Limited (Manual CLI)", E: YES, K: YES, S: YES}},
    {"category": "software_tier", "item_key": "t5-lab", "item_label": "Tier 5: sentinel-lab (Academic Testbed)",
     "item_sub": "MIT License (Open Access / Zenodo)", "values": {C: YES, E: YES, K: YES, S: YES}},
    {"category": "software_tier", "item_key": "t6-nexus", "item_label": "Tier 6: sentinel-nexus (Command Plane)",
     "item_sub": "Node quota check in C++ daemon",
     "values": {C: "Limited (Max 3 Nodes)", E: "✔ Included (Cloud C2)", K: "✔ Included (On-Prem/Cloud)", S: "✔ Included (Multi-Cluster HA)"}},
    {"category": "software_tier", "item_key": "t7-matrix", "item_label": "Tier 7: sentinel-matrix (Cyber-Range)",
     "item_sub": "Docker Compose profile entitlement",
     "values": {C: "Limited (Basic Traffic)", E: "✔ Included (API/Web)", K: "✔ Included (Full OT Mesh)", S: "✔ Included (Full Digital Twin)"}},
    {"category": "software_tier", "item_key": "t8-stack", "item_label": "Tier 8: sentinel-stack (Meta-Installer)",
     "item_sub": "Apache 2.0 (Open Source)", "values": {C: YES, E: YES, K: YES, S: YES}},
    # ---- 26 subsystems ----
    {"category": "security_subsystem", "item_key": "01_siem_core", "item_label": "01_siem_core (SIEM Core)",
     "item_sub": "In-memory log correlation & indexer", "values": {C: YES, E: YES, K: YES, S: YES}},
    {"category": "security_subsystem", "item_key": "02_ueba", "item_label": "02_ueba (User Entity Behavior Analytics)",
     "item_sub": "100k+ in-memory entity behavioral matrix", "values": {C: NO, E: YES, K: YES, S: YES}},
    {"category": "security_subsystem", "item_key": "03_ndr", "item_label": "03_ndr (Network Detection & Response)",
     "item_sub": "Encrypted Traffic Analysis (JA3/JA4 TLS)", "values": {C: NO, E: YES, K: YES, S: YES}},
    {"category": "security_subsystem", "item_key": "04_ids_ips", "item_label": "04_ids_ips (Inline Packet Filter)",
     "item_sub": "Signature matching & local eBPF drops", "values": {C: YES, E: YES, K: YES, S: YES}},
    {"category": "security_subsystem", "item_key": "05_waf", "item_label": "05_waf (Web App & API Protection)",
     "item_sub": "In-kernel SQLi, XSS, BOLA/IDOR blocker", "values": {C: NO, E: YES, K: YES, S: YES}},
    {"category": "security_subsystem", "item_key": "06_edr", "item_label": "06_edr (Endpoint Detection & Response)",
     "item_sub": "Process tree analyzer & memory injection hunter", "values": {C: NO, E: YES, K: YES, S: YES}},
    {"category": "security_subsystem", "item_key": "07_epp_ngav", "item_label": "07_epp_ngav (Next-Gen Antivirus)",
     "item_sub": "Real-time file Shannon entropy calculator", "values": {C: NO, E: YES, K: YES, S: YES}},
    {"category": "security_subsystem", "item_key": "08_nac", "item_label": "08_nac (Network Access Control)",
     "item_sub": "802.1X dynamic VLAN quarantine controller", "values": {C: NO, E: YES, K: YES, S: YES}},
    {"category": "security_subsystem", "item_key": "09_cwpp", "item_label": "09_cwpp (Container Workload Guard)",
     "item_sub": "eBPF container breakout guard at sys_enter", "values": {C: NO, E: YES, K: YES, S: YES}},
    {"category": "security_subsystem", "item_key": "10_bad", "item_label": "10_bad (Bot & Automated Abuse Defense)",
     "item_sub": "Kinematic mouse/keystroke curve classifier", "values": {C: NO, E: YES, K: YES, S: YES}},
    {"category": "security_subsystem", "item_key": "11_rasp", "item_label": "11_rasp (Runtime Self-Protection)",
     "item_sub": "In-memory hook execution guard", "values": {C: NO, E: YES, K: YES, S: YES}},
    {"category": "security_subsystem", "item_key": "12_itdr", "item_label": "12_itdr (Identity Threat Detection)",
     "item_sub": "Kerberoasting & Active Directory abuse", "values": {C: NO, E: YES, K: YES, S: YES}},
    {"category": "security_subsystem", "item_key": "13_ddos", "item_label": "13_ddos (Hardware Line-Rate Flood Shaper)",
     "item_sub": "Hardware line-rate flood shaper & SYN cookies", "values": {C: NO, E: YES, K: YES, S: YES}},
    {"category": "security_subsystem", "item_key": "14_ato", "item_label": "14_ato (Account Takeover Guard)",
     "item_sub": "Impossible travel geo-velocity evaluator", "values": {C: NO, E: YES, K: YES, S: YES}},
    {"category": "security_subsystem", "item_key": "15_ngfw", "item_label": "15_ngfw (Next-Gen Firewall DPI)",
     "item_sub": "Deep packet inspection & connection tracking", "values": {C: YES, E: YES, K: YES, S: YES}},
    {"category": "security_subsystem", "item_key": "16_cdr", "item_label": "16_cdr (Content Disarm & Reconstruction)",
     "item_sub": "Active macro/script stripper for PDF/DOCX", "values": {C: NO, E: YES, K: YES, S: YES}},
    {"category": "security_subsystem", "item_key": "17_iot_sec", "item_label": "17_iot_sec (Medical & IoT Security)",
     "item_sub": "DICOM PACS and HL7 v2 medical parser", "values": {C: NO, E: NO, K: YES, S: YES}},
    {"category": "security_subsystem", "item_key": "18_cps_sec", "item_label": "18_cps_sec (SCADA Constraint Validator)",
     "item_sub": "Modbus & DNP3 physical constraint guard", "values": {C: NO, E: NO, K: YES, S: YES}},
    {"category": "security_subsystem", "item_key": "19_swg", "item_label": "19_swg (Secure Web Gateway)",
     "item_sub": "Sovereign outbound egress proxy", "values": {C: YES, E: YES, K: YES, S: YES}},
    {"category": "security_subsystem", "item_key": "20_fse", "item_label": "20_fse (Firmware Security Evaluation)",
     "item_sub": "UEFI/BIOS binary flash memory dissector", "values": {C: NO, E: NO, K: YES, S: YES}},
    {"category": "security_subsystem", "item_key": "21_side_channel", "item_label": "21_side_channel (Hardware Defense)",
     "item_sub": "Acoustic, power & EM emission anomaly analyzer", "values": {C: NO, E: NO, K: YES, S: YES}},
    {"category": "security_subsystem", "item_key": "22_dfir", "item_label": "22_dfir (Digital Forensics IR)",
     "item_sub": "Ring-buffer PCAP evidence carver with SHA-256", "values": {C: YES, E: YES, K: YES, S: YES}},
    {"category": "security_subsystem", "item_key": "23_ai_trism", "item_label": "23_ai_trism (AI Safety Firewall)",
     "item_sub": "LLM prompt injection & token anomaly filter", "values": {C: NO, E: YES, K: YES, S: YES}},
    {"category": "security_subsystem", "item_key": "24_ztna", "item_label": "24_ztna (Zero Trust Regressor)",
     "item_sub": "Dynamic session risk regressor (0.0 - 1.0)", "values": {C: NO, E: YES, K: YES, S: YES}},
    {"category": "security_subsystem", "item_key": "25_fdp", "item_label": "25_fdp (Fraud Detection Platform)",
     "item_sub": "Financial transaction graph anomaly analyzer", "values": {C: NO, E: YES, K: YES, S: YES}},
    {"category": "security_subsystem", "item_key": "26_ddp", "item_label": "26_ddp (Distributed Deception)",
     "item_sub": "Decoy PLCs and honeypot ports on secondary VIPs", "values": {C: NO, E: NO, K: YES, S: YES}},
    # ---- 30 industrial plugins ----
    {"category": "industrial_plugin", "item_key": "libmodbus_dissector", "item_label": "libmodbus_dissector.so",
     "item_sub": "Modbus TCP (Port 502) — Industrial Automation, Power", "values": {C: NO, E: NO, K: YES, S: YES}},
    {"category": "industrial_plugin", "item_key": "libdnp3_dissector", "item_label": "libdnp3_dissector.so",
     "item_sub": "DNP3 (Port 20000) — Substations, Water", "values": {C: NO, E: NO, K: YES, S: YES}},
    {"category": "industrial_plugin", "item_key": "libs7comm_dissector", "item_label": "libs7comm_dissector.so",
     "item_sub": "Siemens S7Comm (Port 102) — Manufacturing, Automotive", "values": {C: NO, E: NO, K: YES, S: YES}},
    {"category": "industrial_plugin", "item_key": "libprofinet_dissector", "item_label": "libprofinet_dissector.so",
     "item_sub": "PROFINET Real-Time — Factory Automation Loops", "values": {C: NO, E: NO, K: YES, S: YES}},
    {"category": "industrial_plugin", "item_key": "libethernet_ip", "item_label": "libethernet_ip.so",
     "item_sub": "EtherNet/IP (CIP) — Rockwell / Allen-Bradley", "values": {C: NO, E: NO, K: YES, S: YES}},
    {"category": "industrial_plugin", "item_key": "libhart_ip", "item_label": "libhart_ip.so",
     "item_sub": "WirelessHART / HART-IP — Refineries, Chemical", "values": {C: NO, E: NO, K: YES, S: YES}},
    {"category": "industrial_plugin", "item_key": "libmitsubishi_melsec", "item_label": "libmitsubishi_melsec.so",
     "item_sub": "MELSEC-Q — Semiconductor Manufacturing", "values": {C: NO, E: NO, K: YES, S: YES}},
    {"category": "industrial_plugin", "item_key": "libomron_fins", "item_label": "libomron_fins.so",
     "item_sub": "Omron FINS Ethernet — Packaging & Conveyor", "values": {C: NO, E: NO, K: YES, S: YES}},
    {"category": "industrial_plugin", "item_key": "libiec104_dissector", "item_label": "libiec104_dissector.so",
     "item_sub": "IEC 60870-5-104 (Port 2404) — Power Grids", "values": {C: NO, E: NO, K: YES, S: YES}},
    {"category": "industrial_plugin", "item_key": "libiec61850_goose", "item_label": "libiec61850_goose.so",
     "item_sub": "IEC 61850 GOOSE (L2) — HV Substation Bus", "values": {C: NO, E: NO, K: YES, S: YES}},
    {"category": "industrial_plugin", "item_key": "libiec61850_mms", "item_label": "libiec61850_mms.so",
     "item_sub": "IEC 61850 MMS — Substation SCADA Gateway", "values": {C: NO, E: NO, K: YES, S: YES}},
    {"category": "industrial_plugin", "item_key": "libopc_ua_dissector", "item_label": "libopc_ua_dissector.so",
     "item_sub": "OPC UA Binary (Port 4840) — Industry 4.0 Hub", "values": {C: NO, E: NO, K: YES, S: YES}},
    {"category": "industrial_plugin", "item_key": "libbacnet_building", "item_label": "libbacnet_building.so",
     "item_sub": "BACnet/IP (Port 47808) — Smart Buildings", "values": {C: NO, E: YES, K: YES, S: YES}},
    {"category": "industrial_plugin", "item_key": "libmodbus_rtu_serial", "item_label": "libmodbus_rtu_serial.so",
     "item_sub": "Serial Modbus RTU / RS-485 — Legacy Fieldbus", "values": {C: NO, E: NO, K: YES, S: YES}},
    {"category": "industrial_plugin", "item_key": "libenip_cip", "item_label": "libenip_cip.so",
     "item_sub": "Common Industrial Protocol — Robotic Assembly", "values": {C: NO, E: NO, K: YES, S: YES}},
    {"category": "industrial_plugin", "item_key": "libfieldbus_h1", "item_label": "libfieldbus_h1.so",
     "item_sub": "Foundation Fieldbus H1 — Process Instrumentation", "values": {C: NO, E: NO, K: YES, S: YES}},
    {"category": "industrial_plugin", "item_key": "libmavlink_uav", "item_label": "libmavlink_uav.so",
     "item_sub": "MAVLink UAV — Drones & Autonomous Robotics", "values": {C: NO, E: NO, K: YES, S: YES}},
    {"category": "industrial_plugin", "item_key": "libais_maritime", "item_label": "libais_maritime.so",
     "item_sub": "AIS Maritime Transponder — Shipping, Ports", "values": {C: NO, E: NO, K: YES, S: YES}},
    {"category": "industrial_plugin", "item_key": "libnmea_gps", "item_label": "libnmea_gps.so",
     "item_sub": "NMEA-0183/2000 GPS — Navigation Spoofing", "values": {C: NO, E: NO, K: YES, S: YES}},
    {"category": "industrial_plugin", "item_key": "libadsb_avionics", "item_label": "libadsb_avionics.so",
     "item_sub": "ADS-B Mode-S — Air Traffic Management", "values": {C: NO, E: NO, K: YES, S: YES}},
    {"category": "industrial_plugin", "item_key": "libstanag_4586", "item_label": "libstanag_4586.so",
     "item_sub": "NATO STANAG 4586 UAV — Military Datalinks", "values": {C: NO, E: NO, K: NO, S: YES}},
    {"category": "industrial_plugin", "item_key": "libmil_std_1553", "item_label": "libmil_std_1553.so",
     "item_sub": "MIL-STD-1553 Avionics — Fighters, Armor", "values": {C: NO, E: NO, K: NO, S: YES}},
    {"category": "industrial_plugin", "item_key": "libcanbus_automotive", "item_label": "libcanbus_automotive.so",
     "item_sub": "CAN 2.0B / CAN-FD — Connected Vehicle ECUs", "values": {C: NO, E: NO, K: YES, S: YES}},
    {"category": "industrial_plugin", "item_key": "libdicom_pacs", "item_label": "libdicom_pacs.so",
     "item_sub": "DICOM C-STORE — Hospital Radiology / MRI", "values": {C: NO, E: NO, K: YES, S: YES}},
    {"category": "industrial_plugin", "item_key": "libhl7_v2", "item_label": "libhl7_v2.so",
     "item_sub": "HL7 v2 Clinical Messaging — Patient Diagnostics", "values": {C: NO, E: NO, K: YES, S: YES}},
    {"category": "industrial_plugin", "item_key": "libcef_forwarder", "item_label": "libcef_forwarder.so",
     "item_sub": "CEF — Enterprise SIEM Integration", "values": {C: YES, E: YES, K: YES, S: YES}},
    {"category": "industrial_plugin", "item_key": "libleef_forwarder", "item_label": "libleef_forwarder.so",
     "item_sub": "IBM QRadar LEEF — Enterprise SIEM Integration", "values": {C: YES, E: YES, K: YES, S: YES}},
    {"category": "industrial_plugin", "item_key": "libsyslog_rfc5424", "item_label": "libsyslog_rfc5424.so",
     "item_sub": "Syslog RFC 5424 — Universal Log Ingestion", "values": {C: YES, E: YES, K: YES, S: YES}},
    {"category": "industrial_plugin", "item_key": "libkafka_producer", "item_label": "libkafka_producer.so",
     "item_sub": "Apache Kafka Zero-Copy — Enterprise Streaming Lakes", "values": {C: NO, E: YES, K: YES, S: YES}},
    {"category": "industrial_plugin", "item_key": "libsnmp_v3_trap", "item_label": "libsnmp_v3_trap.so",
     "item_sub": "SNMPv3 Encrypted Traps — Network Device Telemetry", "values": {C: YES, E: YES, K: YES, S: YES}},
    {"category": "industrial_plugin", "item_key": "libnetflow_v9_ipfix", "item_label": "libnetflow_v9_ipfix.so",
     "item_sub": "IPFIX / NetFlow v9 Blaster — Wire-Speed Flow Extraction", "values": {C: YES, E: YES, K: YES, S: YES}},
    # ---- 28 cloud SaaS services ----
    {"category": "cloud_saas", "item_key": "saas-nexus-cloud", "item_label": "1 · Sentinel Nexus Cloud",
     "item_sub": "Fleet C2 — Multi-tenant cloud command center",
     "values": {C: "✖ (Local only, ≤ 3)", E: YES, K: YES, S: YES}},
    {"category": "cloud_saas", "item_key": "saas-ztp", "item_label": "2 · Zero-Touch Provisioning (ZTP)",
     "item_sub": "Fleet C2 — Automated cloud enrollment via TPM 2.0", "values": {C: NO, E: YES, K: YES, S: YES}},
    {"category": "cloud_saas", "item_key": "saas-mssp", "item_label": "3 · Multi-Tenant MSSP Portal",
     "item_sub": "Fleet C2 — Hierarchical multi-client management", "values": {C: NO, E: YES, K: YES, S: YES}},
    {"category": "cloud_saas", "item_key": "saas-compiler", "item_label": "4 · xInfer Compiler Cloud",
     "item_sub": "AI & Silicon — Cross-compile for 15 silicon targets",
     "values": {C: NO, E: "50 builds/mo", K: "250 builds/mo", S: "Unlimited Dedicated"}},
    {"category": "cloud_saas", "item_key": "saas-federated", "item_label": "5 · Federated Continual Retraining",
     "item_sub": "AI & Silicon — Cross-fleet privacy-preserving tuning", "values": {C: NO, E: NO, K: YES, S: YES}},
    {"category": "cloud_saas", "item_key": "saas-trism", "item_label": "6 · AI TRiSM Gateway",
     "item_sub": "AI & Silicon — LLM prompt injection firewall proxy",
     "values": {C: NO, E: "50k tokens/mo", K: "1M tokens/mo", S: "Unlimited Dedicated"}},
    {"category": "cloud_saas", "item_key": "saas-feed", "item_label": "7 · Global Collective Defense Feed",
     "item_sub": "CTI — Sub-50ms crowdsourced zero-day feed", "values": {C: NO, E: YES, K: YES, S: YES}},
    {"category": "cloud_saas", "item_key": "saas-ot-feed", "item_label": "8 · OT/SCADA Exploit Warning Feed",
     "item_sub": "CTI — Early warning for weaponized PLC exploits", "values": {C: NO, E: NO, K: YES, S: YES}},
    {"category": "cloud_saas", "item_key": "saas-ransomware", "item_label": "9 · Ransomware IOC Clearinghouse",
     "item_sub": "CTI — Real-time high-entropy process hash registry", "values": {C: NO, E: YES, K: YES, S: YES}},
    {"category": "cloud_saas", "item_key": "saas-nis2", "item_label": "10 · Automated EU NIS2 / DORA Vault",
     "item_sub": "Compliance — Timestamped incident SLA proofs", "values": {C: NO, E: YES, K: YES, S: YES}},
    {"category": "cloud_saas", "item_key": "saas-cmmc", "item_label": "11 · CMMC 2.0 / NIST 800-171 Vault",
     "item_sub": "Compliance — Assessor-ready packages with TPM quotes", "values": {C: NO, E: NO, K: YES, S: YES}},
    {"category": "cloud_saas", "item_key": "saas-insurance", "item_label": "12 · Cyber Insurance Risk Verifier",
     "item_sub": "Compliance — Proof for 20%–40% premium cuts", "values": {C: NO, E: YES, K: YES, S: YES}},
    {"category": "cloud_saas", "item_key": "saas-sbom", "item_label": "13 · Dynamic SBOM & VEX Tracker",
     "item_sub": "Compliance — Cloud CycloneDX/SPDX vulnerability indexer", "values": {C: NO, E: YES, K: YES, S: YES}},
    {"category": "cloud_saas", "item_key": "saas-scada", "item_label": "14 · SCADA Actuator Analytics",
     "item_sub": "CPS Security — Long-term PLC chatter & wear analysis", "values": {C: NO, E: NO, K: YES, S: YES}},
    {"category": "cloud_saas", "item_key": "saas-medical", "item_label": "15 · Medical IoMT & DICOM Cloud",
     "item_sub": "CPS Security — Hospital radiology security hub", "values": {C: NO, E: NO, K: YES, S: YES}},
    {"category": "cloud_saas", "item_key": "saas-maritime", "item_label": "16 · Maritime & Vessel Fleet Portal",
     "item_sub": "CPS Security — Low-bandwidth satellite tracking", "values": {C: NO, E: NO, K: YES, S: YES}},
    {"category": "cloud_saas", "item_key": "saas-itdr", "item_label": "17 · Identity Threat (ITDR) Cloud",
     "item_sub": "Identity — Entra ID & AD abuse monitoring", "values": {C: NO, E: YES, K: YES, S: YES}},
    {"category": "cloud_saas", "item_key": "saas-botapi", "item_label": "18 · Kinematic Bot Defense API",
     "item_sub": "Identity — Web API scoring trajectory curves",
     "values": {C: NO, E: "100k req/mo", K: "1M req/mo", S: "Unlimited Dedicated"}},
    {"category": "cloud_saas", "item_key": "saas-deception", "item_label": "19 · Deception & Honeypot Cloud",
     "item_sub": "Identity — Remote VIP rotation of decoy PLCs", "values": {C: NO, E: NO, K: YES, S: YES}},
    {"category": "cloud_saas", "item_key": "saas-ztna", "item_label": "20 · Dynamic Zero Trust Scorer",
     "item_sub": "Identity — Real-time session risk scoring (0.0 - 1.0)", "values": {C: NO, E: YES, K: YES, S: YES}},
    {"category": "cloud_saas", "item_key": "saas-vault", "item_label": "21 · Cloud Evidence Vault (PCAP)",
     "item_sub": "Forensics — Signed PCAP with legal chain-of-custody",
     "values": {C: NO, E: "10 GB Storage", K: "100 GB Storage", S: "Unlimited Storage"}},
    {"category": "cloud_saas", "item_key": "saas-cdr", "item_label": "22 · Cloud CDR Document Sanitizer",
     "item_sub": "Forensics — Cloud API stripping macros from PDF/DOCX",
     "values": {C: NO, E: "500 docs/mo", K: "5,000 docs/mo", S: "Unlimited Dedicated"}},
    {"category": "cloud_saas", "item_key": "saas-firmware", "item_label": "23 · Firmware Backdoor Scanner",
     "item_sub": "Forensics — Static analysis for router/PLC firmware",
     "values": {C: NO, E: NO, K: "10 scans/mo", S: "Unlimited Dedicated"}},
    {"category": "cloud_saas", "item_key": "saas-twin", "item_label": "24 · Matrix Digital Twin Cyber-Range",
     "item_sub": "Simulation — Cloud-hosted virtual replica of plants",
     "values": {C: NO, E: "10 hours/mo", K: "50 hours/mo", S: "Unlimited Dedicated"}},
    {"category": "cloud_saas", "item_key": "saas-bas", "item_label": "25 · Automated Breach Simulation (BAS)",
     "item_sub": "Simulation — Scheduled nmap/Modbus attack sims",
     "values": {C: NO, E: "1 run/mo", K: "10 runs/mo", S: "Continuous Daily"}},
    {"category": "cloud_saas", "item_key": "saas-resilience", "item_label": "26 · Resilience & MTTR Certification",
     "item_sub": "Simulation — Certified Mean Time to Fleet Immunity",
     "values": {C: NO, E: "Annual Audit", K: "Semi-Annual Audit", S: "Continuous Audit"}},
    {"category": "cloud_saas", "item_key": "saas-mdr", "item_label": "27 · Co-Managed CPS SOC (MDR)",
     "item_sub": "Managed — 24/7 human-in-the-loop alert triage",
     "values": {C: NO, E: "Optional Add-on", K: YES, S: "Dedicated Analysts"}},
    {"category": "cloud_saas", "item_key": "saas-ir", "item_label": "28 · Incident Response Guarantee",
     "item_sub": "Managed — Emergency on-demand kernel & SCADA response",
     "values": {C: NO, E: "4-Hour SLA", K: "1-Hour SLA", S: "15-Minute Critical SLA"}},
]

CATEGORIES = [
    ("software_tier", "Core Software Tiers", 8),
    ("security_subsystem", "Security Subsystems", 26),
    ("industrial_plugin", "Industrial Plugins", 30),
    ("cloud_saas", "Cloud SaaS Services", 28),
]
